use datafusion::sql::ResolvedTableReference;
use std::fmt::Display;
use std::sync::Arc;

/// Specifies the use for identifiers generated by a [KeyManager].
#[derive(Debug, Clone, Eq, PartialEq, Hash)]
pub enum IdentifierContext {
    RowIdColumn {
        table_context: ResolvedTableReference,
    },
    /// Generate stable values for use in a non-versioned index
    NamedIndexInTable {
        table_context: ResolvedTableReference,
        index_name: Arc<str>,
    },
    /// Generate stable values for use in a versioned index
    NamedVersionedIndexInTable {
        table_context: ResolvedTableReference,
        index_name: Arc<str>,
        version_number: u64,
    },
}

impl Display for IdentifierContext {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            IdentifierContext::NamedIndexInTable {
                table_context,
                index_name,
            } => {
                write!(f, "named_index({table_context},{index_name})")
            }
            IdentifierContext::RowIdColumn { table_context } => {
                write!(f, "row_id({table_context})")
            }
            IdentifierContext::NamedVersionedIndexInTable {
                table_context,
                index_name,
                version_number,
            } => {
                write!(
                    f,
                    "versioned_index({table_context},{index_name},v{version_number})"
                )
            }
        }
    }
}

/// Specifies the use for a cipher. These parameters are roughly parameters for the key-derivation
/// function - a different key being derived for different contexts.
#[derive(Debug, Clone, Eq, PartialEq, Hash)]
pub enum CipherContext {
    /// The cipher is used to encrypt values in a column in a table
    TableColumn {
        table_context: ResolvedTableReference,
        column_name: Arc<str>,
    },
    /// The cipher is used to encrypt pages of a versioned index
    VersionedIndexEntry {
        table_context: ResolvedTableReference,
        index_name: Arc<str>,
        version_number: Option<u64>,
    },
}
