use crate::arrow_helper::project_schema_safe;
use crate::metadata;
use crate::metadata::{
    ColumnName, EncryptedColumnMeta, EncryptedTableMeta, IndexInsertStrategy, IndexQueryStrategy,
    PrimaryKey, PrimaryKeyColumnDef, compute_expected_indexable_column_type,
};
use crate::planning::logical::CURRENT_VALUE_PREFIX;
use crate::planning::physical::locking::transform_select_with_locking;
use crate::planning::physical::plans::mysql_scan_plan::MySqlScanPlan;
use crate::providers::parser::{parse_column_type, parse_default_value_to_expr};
use crate::sinks::multiplex_sink::MultiplexSink;
use crate::sinks::mysql_delete_sink::MySqlDeleteSink;
use crate::sinks::mysql_dml_sink::MySqlDmlSink;
use crate::sinks::sink::{RecordBatchSink, RecordBatchSinkExec};
use async_trait::async_trait;
use common::conversions::column_def_ext::ColumnDefExt;
use common::conversions::datatypes::ArrowDatatypeConverter;
use common::metadata::{MetadataReads, MetadataWrites};
use crypto::cipher::AssociatedData;
use crypto::key_manager::KeyManager;
use crypto::planning::decrypt_planner::project_decrypt;
use crypto::planning::physical::encrypt::EncryptExpr;
use crypto::planning::physical::to_binary::ToBinaryExpr;
use crypto::{CipherContext, KeyManagerGetter};
use datafusion::arrow::array::{BinaryBuilder, RecordBatch};
use datafusion::arrow::datatypes::{DataType, Field, FieldRef, Schema, SchemaRef};
use datafusion::catalog::{Session, TableProvider};
use datafusion::common::tree_node::{Transformed, TreeNode, TreeNodeRecursion};
use datafusion::common::{Column, Constraint, Constraints, DFSchema, Statistics, plan_err};
use datafusion::datasource::TableType;
use datafusion::error::DataFusionError;
use datafusion::logical_expr::dml::InsertOp;
use datafusion::logical_expr::{
    BinaryExpr, ColumnarValue, Expr, LogicalPlan, Operator, TableProviderFilterPushDown,
};
use datafusion::physical_expr;
use datafusion::physical_expr::PhysicalExpr;
use datafusion::physical_plan::ExecutionPlan;
use datafusion::physical_plan::display::DisplayableExecutionPlan;
use datafusion::physical_plan::projection::{ProjectionExec, ProjectionExpr};
use datafusion::prelude::SessionContext;
use datafusion::sql::TableReference;
use datafusion::sql::sqlparser::ast::{ColumnDef, LockType};
use datafusion::sql::unparser::Unparser;
use datafusion::sql::unparser::dialect::MySqlDialect;
use log::trace;
use mysql_async::prelude::Queryable;
use mysql_async::{Conn, TxOpts};
use rand::{RngCore, rng};
use rustc_hash::{FxHashMap, FxHashSet};
use serde::{Deserialize, Serialize};
use std::any::Any;
use std::borrow::Cow;
use std::fmt::{Display, Formatter};
use std::iter;
use std::iter::once;
use std::sync::Arc;

#[derive(Debug, Clone)]
pub enum ColumnDefault {
    Expr(Expr),
    AutoIncrement,
}

#[derive(Debug, Clone)]
pub(crate) struct MySqlTableProvider {
    pub(crate) table_reference: TableReference,
    table_type: TableType,
    table_schema: SchemaRef,
    pub(crate) columns_defaults: FxHashMap<String, ColumnDefault>,
    encryption_metadata: EncryptedTableMeta,

    constraints: Constraints,
    primary_key: Vec<ColumnName>,

    indexable_column: Option<Field>,
    indexable_column_type: IndexableColumn,
}

#[derive(Debug, Copy, Clone, Deserialize, Serialize, PartialEq, Eq, Hash)]
pub enum IndexableColumnSize {
    B8,
    B16,
    B32,
    B64,
    B96,
    B128,
}

impl IndexableColumnSize {
    fn bytes(&self) -> usize {
        match self {
            IndexableColumnSize::B8 => 1,
            IndexableColumnSize::B16 => 2,
            IndexableColumnSize::B32 => 4,
            IndexableColumnSize::B64 => 8,
            IndexableColumnSize::B96 => 12,
            IndexableColumnSize::B128 => 16,
        }
    }

    pub fn random_value(&self) -> Vec<u8> {
        let mut vec = vec![0u8; self.bytes()];
        rng().fill_bytes(&mut vec);
        vec
    }
}

const GENERATED_INDEXABLE_COLUMN_NAME: &str = "__fusionindex";

#[derive(Debug, Copy, Clone, Deserialize, Serialize, PartialEq, Eq)]
pub enum IndexableColumn {
    /// The indexable column is generated randomly
    RandomGenerated(IndexableColumnSize),

    /// The indexable column is a native SQL column, without any auto-generation
    /// It must be the unique primary key of the table
    UserProvided(IndexableColumnSize),
}

impl IndexableColumn {
    /// Returns true if this indexable column is generated by the proxy when inserting the value
    pub fn is_generated(&self) -> bool {
        match self {
            IndexableColumn::RandomGenerated(_) => true,
            IndexableColumn::UserProvided(_) => false,
        }
    }

    pub fn size(&self) -> IndexableColumnSize {
        match self {
            IndexableColumn::RandomGenerated(s) | IndexableColumn::UserProvided(s) => *s,
        }
    }
}

impl MySqlTableProvider {
    pub fn get_indexable_column_type(&self) -> IndexableColumn {
        self.indexable_column_type
    }

    pub fn get_indexable_column(&self) -> Option<Field> {
        if self.get_indexable_column_type().is_generated() {
            self.indexable_column.clone()
        } else {
            assert_eq!(self.primary_key.len(), 1);
            let field = self
                .table_schema
                .field_with_name(&self.primary_key[0])
                .expect("primary key must exist");
            Some(field.clone())
        }
    }

    pub async fn create_indexable_column(
        &mut self,
        conn: &mut Conn,
    ) -> datafusion::common::Result<()> {
        let column_type = self.get_indexable_column_type();
        if !column_type.is_generated() {
            panic!("Cannot create a non generated indexable column - it should already exist")
        }

        let table_ref = format!(
            "{}.{}",
            self.table_reference.schema().unwrap(),
            self.table_reference.table()
        );

        let mut txn = conn
            .start_transaction(TxOpts::new())
            .await
            .map_err(|e| DataFusionError::Execution(e.to_string()))?;

        // 1. Create the column with an index
        txn.query_drop(format!(
            "ALTER TABLE {table_ref} \
                ADD COLUMN {GENERATED_INDEXABLE_COLUMN_NAME} BINARY({}) NULL,\
                ADD UNIQUE INDEX ({GENERATED_INDEXABLE_COLUMN_NAME})",
            column_type.size().bytes()
        ))
        .await
        .map_err(|e| {
            DataFusionError::Execution(format!("Failed to create the indexable column: {e}"))
        })?;

        // 2. Fill it with random values
        txn.query_drop(format!(
            "UPDATE {table_ref} SET {GENERATED_INDEXABLE_COLUMN_NAME} = RANDOM_BYTES({})",
            column_type.size().bytes()
        ))
        .await
        .map_err(|e| {
            DataFusionError::Execution(format!("Failed to fill the indexable column: {e}"))
        })?;

        // 3. Set it NOT NULL
        txn.query_drop(format!(
            "ALTER TABLE {table_ref} MODIFY {GENERATED_INDEXABLE_COLUMN_NAME} BINARY({}) NOT NULL",
            column_type.size().bytes()
        ))
        .await
        .map_err(|e| {
            DataFusionError::Execution(format!("Failed to create the indexable column: {e}"))
        })?;

        txn.commit()
            .await
            .map_err(|e| DataFusionError::Execution(e.to_string()))?;

        self.indexable_column = Some(Field::new(
            GENERATED_INDEXABLE_COLUMN_NAME,
            DataType::Binary,
            false,
        ));

        Ok(())
    }

    // TODO: When initializing the table, ensure the column is present and set in metadata

    fn build_schema(
        table_name: &str,
        columns: &[ColumnDef],
        encryption_metadata: &Option<EncryptedTableMeta>,
    ) -> datafusion::common::Result<Schema> {
        if let Some(encryption_metadata) = encryption_metadata {
            let fields = columns
                .iter()
                .filter(|column| !encryption_metadata.is_column_hidden(&column.name.value))
                .map(|column| {
                    Self::build_field_from_column_def(
                        table_name,
                        column,
                        encryption_metadata.column(&column.name.value),
                    )
                })
                .collect::<Result<Vec<_>, _>>()?;

            Ok(Schema::new(fields))
        } else {
            ArrowDatatypeConverter.table_to_schema(columns)
        }
    }

    pub fn build_field_from_column_def(
        table_name: &str,
        column: &ColumnDef,
        column_meta: Option<&EncryptedColumnMeta>,
    ) -> datafusion::common::Result<Field> {
        let Some(column_meta) = column_meta else {
            return ArrowDatatypeConverter.column_to_field(column);
        };

        let mut field = Field::new(
            column.name.value.clone(),
            column_meta.data_type(),
            column_meta.nullable,
        );

        field.set_raw_source_type(column_meta.original_type_raw.clone());

        if let Some(expr) = column_meta.default_value_raw.clone() {
            field.set_default_value(expr);
        }

        if let Some(collation) = column_meta.collation.clone() {
            field.set_raw_collation(collation);
        }

        field.set_encrypted(table_name);

        Ok(field)
    }

    pub fn build_column_default(
        column_def: &ColumnDef,
        field: &FieldRef,
    ) -> datafusion::common::Result<Option<ColumnDefault>> {
        let default_expr = if field.is_encrypted() {
            let base_data_type = field
                .raw_source_type()
                .map(|ct| parse_column_type(ct).expect("invalid data type for encrypted column"))
                .expect("missing data type for encrypted column");

            let Some(default_value) = field.default_value() else {
                return Ok(None);
            };

            Some(parse_default_value_to_expr(default_value, &base_data_type)?)
        } else {
            column_def.get_default_value()
        };

        if let Some(dv) = default_expr {
            let ctx = SessionContext::new();
            let default_value = ctx
                .state()
                .create_logical_expr(&dv.to_string(), &DFSchema::empty())?;

            return Ok(Some(ColumnDefault::Expr(default_value)));
        }

        Ok(if column_def.is_auto_increment() {
            Some(ColumnDefault::AutoIncrement)
        } else {
            None
        })
    }

    /// Returns a list of all tables that are related to this tables, for example index tables.
    pub fn linked_table_names(&self) -> Vec<String> {
        self.encryption_metadata
            .indices()
            .iter()
            .flat_map(|index| index.linked_table_names())
            .collect()
    }

    pub(crate) fn from_columns(
        table_reference: TableReference,
        columns: Vec<ColumnDef>,
        primary_key: Vec<ColumnName>,
        encryption_metadata: Option<EncryptedTableMeta>,
    ) -> Self {
        // Remove catalog from table reference
        let table_reference = match table_reference {
            TableReference::Full { table, schema, .. } => TableReference::Partial { table, schema },
            other => other,
        };

        // Determine primary keys
        let constraints = if primary_key.is_empty() {
            Vec::new()
        } else {
            let primary_key_indices = columns
                .iter()
                .enumerate()
                .filter_map(|(index, col)| {
                    if primary_key.contains(&col.name.value) {
                        Some(index)
                    } else {
                        None
                    }
                })
                .collect();

            vec![Constraint::PrimaryKey(primary_key_indices)]
        };
        let constraints = Constraints::new_unverified(constraints);

        let (indexable_column, columns) = columns
            .into_iter()
            .partition::<Vec<_>, _>(|item| &item.name.value == GENERATED_INDEXABLE_COLUMN_NAME);

        // Build schema
        let schema =
            Self::build_schema(table_reference.table(), &columns, &encryption_metadata).unwrap();

        // Build indexable column if present
        let indexable_column = indexable_column
            .first()
            .and_then(|col| ArrowDatatypeConverter.column_to_field(col).ok());

        let defaults = columns
            .iter()
            .zip(schema.fields().iter())
            .filter_map(|(column_def, field)| {
                match Self::build_column_default(column_def, field) {
                    Ok(v) => v.map(|default| (column_def.name.value.clone(), default)),
                    Err(e) => {
                        match column_def.get_default_value() {
                            None => {
                                log::warn!("Failed to parse column default for encrypted column {} in table {table_reference}: {e:?}", &column_def.name,);
                            }
                            Some(default_value) => {
                                log::warn!("Failed to parse column default for encrypted column {} (`{}`) in table {table_reference}: {e:?}", &column_def.name, default_value);
                            }
                        }
                        None
                    }
                }
            })
            .collect::<FxHashMap<_, _>>();

        let full_primary_key: PrimaryKey = primary_key
            .iter()
            .filter_map(|column_name| {
                let data_type = schema
                    .field_with_name(column_name)
                    .ok()?
                    .data_type()
                    .clone();

                Some(PrimaryKeyColumnDef {
                    column_name: column_name.clone(),
                    column_type: data_type,
                    has_default: defaults.contains_key(column_name),
                })
            })
            .collect();

        let mut encryption_metadata =
            encryption_metadata.unwrap_or_else(|| EncryptedTableMeta::new());

        let indexable_column_type = compute_expected_indexable_column_type(&full_primary_key);
        encryption_metadata.set_indexable_column(indexable_column_type);
        // TODO: verify this is in adequation with the actual column type...
        // TODO: This whole metadata initialization is a complete mess and should be refactored

        let primary_key = full_primary_key
            .into_iter()
            .map(|data| data.column_name)
            .collect();

        Self {
            columns_defaults: defaults,
            table_schema: SchemaRef::new(schema),
            table_type: TableType::Base,
            table_reference,
            constraints,
            encryption_metadata,
            primary_key,
            indexable_column,
            indexable_column_type,
        }
    }

    pub(crate) fn is_column_encrypted(&self, col: &Column) -> bool {
        // If relation is present, verify it
        if col.relation.is_some()
            && col
                .relation
                .as_ref()
                .is_none_or(|inner| inner.table() != self.table_reference.table())
        {
            return false;
        }

        self.is_encrypted(&col.name)
    }

    #[allow(unused)]
    pub(crate) fn has_encrypted_columns(&self) -> bool {
        self.encryption_metadata.has_encrypted_column()
    }

    #[allow(unused)]
    pub(crate) fn has_indices(&self) -> bool {
        !self.encryption_metadata.indices().is_empty()
    }

    /// Returns the list of all columns that are tracked by complex indices.
    /// If these columns are modified, their current value must be queried for the index.
    #[allow(unused)]
    pub(crate) fn columns_with_updates_tracking(&self) -> FxHashSet<ColumnName> {
        self.encryption_metadata
            .indices()
            .iter()
            .filter(|index| index.requires_old_value_on_update())
            .flat_map(|index| index.tracked_columns())
            .collect()
    }

    /// True if this table has one or more indexes that are not in this table
    /// If true, this means that some DML operations require additional queries to modify the
    /// additional structure
    pub(crate) fn has_index_storage(&self) -> bool {
        self.encryption_metadata
            .indices()
            .iter()
            .any(|index| index.requires_external_storage())
    }

    pub(crate) fn is_encrypted(&self, col_name: &ColumnName) -> bool {
        self.get_column_metadata(col_name).is_some()
    }

    pub(crate) fn get_column_metadata(
        &self,
        col_name: &ColumnName,
    ) -> Option<&metadata::EncryptedColumnMeta> {
        self.encryption_metadata.column(col_name)
    }

    pub(crate) fn primary_key(&self) -> &Vec<ColumnName> {
        &self.primary_key
    }

    pub(crate) fn encryption_metadata(&self) -> &EncryptedTableMeta {
        &self.encryption_metadata
    }

    pub(crate) fn encryption_metadata_mut(&mut self) -> &mut EncryptedTableMeta {
        // If we reach this point of the code, the column MUST exist
        &mut self.encryption_metadata
    }

    fn filter_supported_for_expr(
        &self,
        expr: &Expr,
    ) -> datafusion::common::Result<TableProviderFilterPushDown> {
        let mut output = TableProviderFilterPushDown::Exact;

        expr.apply(|expr| match expr {
            Expr::Column(col) => {
                if let Some(relation) = col.relation.as_ref() {
                    if relation.table() != self.table_reference.table()
                        || relation.schema().is_some_and(|schema| {
                            self.table_reference
                                .schema()
                                .is_some_and(|self_schema| schema != self_schema)
                        })
                    {
                        output = TableProviderFilterPushDown::Unsupported;
                        return Ok(TreeNodeRecursion::Stop);
                    }
                }

                // Is the column in the schema?
                if self.schema().column_with_name(col.name()).is_none() {
                    output = TableProviderFilterPushDown::Unsupported;
                    return Ok(TreeNodeRecursion::Stop);
                }

                // For a column, we always report Partial if it's an encrypted column
                if self.is_column_encrypted(col) {
                    output = TableProviderFilterPushDown::Inexact
                };
                Ok(TreeNodeRecursion::Continue)
            }
            Expr::ScalarSubquery(_) | Expr::InSubquery(_) | Expr::Exists(_) => {
                // TODO: some queries we may actually be able to forward... Check if any node is an extension?
                output = TableProviderFilterPushDown::Unsupported;
                return Ok(TreeNodeRecursion::Stop);
            }
            _ => Ok(TreeNodeRecursion::Continue),
        })?;

        Ok(output)
    }

    pub async fn scan_and_decrypt_all(
        &self,
        state: &dyn Session,
        projection: Schema,
        filters: &[Expr],
        limit: Option<usize>,
    ) -> datafusion::common::Result<Arc<dyn ExecutionPlan>> {
        let encrypted_column_meta = projection
            .fields()
            .iter()
            .map(|field| {
                self.get_column_metadata(field.name()).map(|col_meta| {
                    crypto::encrypted_column_meta::EncryptedColumnMeta {
                        table: self.table_reference.table().to_string(),
                        column: field.name().clone(),
                        original_type: col_meta.original_type.clone(),
                    }
                })
            })
            .collect::<Vec<_>>();

        let keys_manager = state.config().get_long_term_keys_manager();
        let decrypt_projection = project_decrypt(
            &projection,
            encrypted_column_meta.as_slice(),
            keys_manager.as_ref(),
        )?;

        let base_plan = self
            .scan_with_schema(state, projection.clone(), filters, limit)
            .await?;
        let plan = ProjectionExec::try_new(decrypt_projection, base_plan)?;
        Ok(Arc::new(plan))
    }

    pub async fn scan_with_schema(
        &self,
        state: &dyn Session,
        projection: Schema,
        filters: &[Expr],
        limit: Option<usize>,
    ) -> datafusion::common::Result<Arc<dyn ExecutionPlan>> {
        let projection = self.transform_encrypted_fields(projection);
        let projected_schema = SchemaRef::new(projection);

        trace!("Scan {:?} with filters: {filters:?}", &self.table_reference);

        let (forwarded_filters, other_filters) = filters
            .iter()
            .cloned()
            .map(|filt| {
                let support_level = self
                    .filter_supported_for_expr(&filt)
                    .unwrap_or(TableProviderFilterPushDown::Unsupported);
                (filt, support_level)
            })
            .partition::<Vec<_>, _>(|(_, support)| support == &TableProviderFilterPushDown::Exact);

        // TODO: (exact) OR (inexact) should be forwarded if we have a filter for the inexact part (otherwise it's useless)

        let (mut forwarded_filters, _): (Vec<Expr>, Vec<_>) = forwarded_filters.into_iter().unzip();

        // TODO: we must insert an index filter when we can

        let key_manager = state.config().get_long_term_keys_manager();
        let mut dynamic_filters = vec![];

        if self.has_indices() {
            let (mut remaining_filters, _): (Vec<_>, Vec<_>) = other_filters.into_iter().unzip();
            // TODO: would be interesting to re-feed accepted filters to other indices, in case we have complex boolean trees

            for index in self.encryption_metadata.indices() {
                if remaining_filters.is_empty() {
                    break;
                }

                let (mut index_filters, other) = remaining_filters
                    .into_iter()
                    .partition(|filter| index.supports_expression(filter));
                remaining_filters = other;

                let new_filter = Arc::clone(index).query(
                    &self,
                    key_manager.clone(),
                    index_filters.as_slice(),
                )?;

                if let Some(new_filter) = new_filter {
                    match new_filter {
                        IndexQueryStrategy::AddFilterExpression(expr) => {
                            forwarded_filters.push(expr);
                        }
                        IndexQueryStrategy::AddDynamicFilterExpression(expr, dynamic_expr) => {
                            forwarded_filters.push(expr);
                            dynamic_filters.push(dynamic_expr);
                        }
                    }
                } else {
                    // No index returned, we re-add the filters in case we can find another one later
                    remaining_filters.append(&mut index_filters);
                }
            }
        }

        let query_builder = Unparser::new(&MySqlDialect {});
        let static_filter = forwarded_filters.into_iter().reduce(|l, r| {
            Expr::BinaryExpr(BinaryExpr {
                left: Box::new(l),
                right: Box::new(r),
                op: Operator::And,
            })
        });

        let static_filter = if let Some(static_filter) = static_filter {
            Some(query_builder.expr_to_sql(&static_filter)?)
        } else {
            None
        };

        let plan: Arc<dyn ExecutionPlan> = Arc::new(MySqlScanPlan::new_from_schema(
            &(self.table_reference.clone().resolve("", "")),
            projected_schema.clone(),
            limit,
            static_filter,
            dynamic_filters,
        ));

        Ok(plan)
    }

    fn transform_encrypted_fields(&self, schema: Schema) -> Schema {
        let fields = schema
            .fields
            .iter()
            .map(|field| {
                if self.is_encrypted(field.name()) {
                    FieldRef::new(
                        Arc::unwrap_or_clone(field.clone()).with_data_type(DataType::Binary),
                    )
                } else {
                    field.clone()
                }
            })
            .collect::<Vec<_>>();

        Schema::new_with_metadata(fields, schema.metadata)
    }

    pub fn update_schema(&mut self, schema: SchemaRef) {
        self.table_schema = schema;
    }
}

// TODO:
// on connection establishment:
// 1. List databases
// 2. Parse Information Schema to extract table information, including statistics and defaults
// 3. Retrieve all variables and set their values

#[async_trait]
impl TableProvider for MySqlTableProvider {
    fn as_any(&self) -> &dyn Any {
        self
    }

    fn schema(&self) -> SchemaRef {
        self.table_schema.clone()
    }

    fn constraints(&self) -> Option<&Constraints> {
        Some(&self.constraints)
    }

    fn table_type(&self) -> TableType {
        self.table_type
    }

    fn get_table_definition(&self) -> Option<&str> {
        None
    }

    fn get_logical_plan(&self) -> Option<Cow<'_, LogicalPlan>> {
        None // TODO: for views?
    }

    fn get_column_default(&self, column: &str) -> Option<&Expr> {
        let default = self.columns_defaults.get(column)?;

        match default {
            ColumnDefault::Expr(ex) => Some(ex),
            ColumnDefault::AutoIncrement => None,
        }
    }

    async fn scan(
        &self,
        state: &dyn Session,
        projection: Option<&Vec<usize>>,
        filters: &[Expr],
        limit: Option<usize>,
    ) -> datafusion::common::Result<Arc<dyn ExecutionPlan>> {
        let schema = project_schema_safe(&self.table_schema, projection)?;
        let result = self
            .scan_with_schema(state, Arc::unwrap_or_clone(schema), filters, limit)
            .await;
        result
    }

    fn supports_filters_pushdown(
        &self,
        filters: &[&Expr],
    ) -> datafusion::common::Result<Vec<TableProviderFilterPushDown>> {
        // TODO: most filters can be pushed down, do we just return true?
        // TODO: detect which functions are unavailable on MySQL?
        // TODO: take encrypted columns into account! (encrypted w/ index: allow pushdown, transparently insert intermediate step to handle index/refiltering ;; encrypted w/o index: disallow pushdown? (or allow and insert decryption step?))

        // We have a single schema here, so all filters should be pushable
        // TODO: ok, the `Inexact` filter is great for encrypted stuff!
        filters
            .iter()
            .map(|&filter| {
                if self.has_encrypted_columns() {
                    let out = self.filter_supported_for_expr(filter);

                    trace!("Filter pushdown [{out:?}]: {filter:?}");

                    out
                } else {
                    // Shortcut for unencrypted tables
                    Ok(TableProviderFilterPushDown::Exact)
                }
            })
            .collect()
    }

    fn statistics(&self) -> Option<Statistics> {
        None // TODO: we can get these stats from the SQL server at startup
    }

    async fn insert_into(
        &self,
        state: &dyn Session,
        input: Arc<dyn ExecutionPlan>,
        insert_op: InsertOp,
    ) -> datafusion::common::Result<Arc<dyn ExecutionPlan>> {
        // TODO: verify that the input schema is respected (in particular non null values)

        // If there is an indexable column, it must be added first so that it is accessible to all indices managed later on
        let input = if let Some(idx) = self.indexable_column.as_ref() {
            let expression = GenerateRandomValue(self.indexable_column_type.size());
            let project_add_indexable_column = input
                .schema()
                .fields()
                .iter()
                .enumerate()
                .map(|(idx, field)| {
                    let base =
                        datafusion::physical_expr::expressions::Column::new(field.name(), idx);
                    ProjectionExpr::new(Arc::new(base), field.name().clone())
                })
                .chain(iter::once(ProjectionExpr::new(
                    Arc::new(expression),
                    idx.name().to_string(),
                )))
                .collect::<Vec<_>>();

            Arc::new(ProjectionExec::try_new(
                project_add_indexable_column,
                input,
            )?) as Arc<dyn ExecutionPlan>
        } else {
            input
        };

        let (projected_input, insert_schema, more_sinks) =
            self.project_insert_update(state, input, false)?;

        let fmt = DisplayableExecutionPlan::new(projected_input.as_ref());
        trace!("INSERT sink: {}", fmt.indent(true));

        let sink = MySqlDmlSink::insert(self.table_reference.clone(), insert_op, insert_schema);
        let sink = Self::chain_sink(Arc::new(sink), more_sinks);
        let exec = RecordBatchSinkExec::new(projected_input, sink);

        Ok(Arc::new(exec))
    }
}

impl MySqlTableProvider {
    pub async fn delete_from(
        &self,
        _state: &dyn Session,
        input: Arc<dyn ExecutionPlan>,
    ) -> datafusion::common::Result<Arc<dyn ExecutionPlan>> {
        // This operation is way simpler than insert, because the projection of the schema is already handled by the logical planner
        // We may need to redo/recheck, though

        // TODO: check to see if the plan is an empty select (full drop)
        let projected_schema = input.schema();

        // TODO: verify that this schema makes sense

        // TODO: update indices

        let sink = MySqlDeleteSink::new(self.table_reference.clone(), projected_schema.clone());
        let exec = RecordBatchSinkExec::new(input, Arc::new(sink));

        Ok(Arc::new(exec))
    }

    pub async fn update(
        &self,
        state: &dyn Session,
        input: Arc<dyn ExecutionPlan>,
    ) -> datafusion::common::Result<Arc<dyn ExecutionPlan>> {
        let input = transform_select_with_locking(input, LockType::Update)?;

        // If we have a generated indexable column, add it to the underlying select plan
        // This cannot be done at logical planning because the indexable column is "invisible".
        let input = if self.get_indexable_column_type().is_generated() && self.has_index_storage() {
            let Some(indexable_column) = self.get_indexable_column() else {
                plan_err!("table must have an indexable column")?
            };

            let indexable_column = Arc::new(indexable_column);
            let table_ref = self.table_reference.clone().resolve("", "");
            let alias = format!("{CURRENT_VALUE_PREFIX}{GENERATED_INDEXABLE_COLUMN_NAME}");

            input
                .transform_up(|node| {
                    let node_ref = node.as_ref().as_any();

                    if node_ref.is::<MySqlScanPlan>() {
                        let Some(plan) = node_ref.downcast_ref::<MySqlScanPlan>() else {
                            unreachable!()
                        };

                        // We want to insert the column to an existing plan...
                        let mut plan = plan.clone();
                        plan.add_select_column(
                            &table_ref,
                            Arc::clone(&indexable_column),
                            Some(&alias),
                        );

                        Ok(Transformed::yes(Arc::new(plan)))
                    } else if node_ref.is::<ProjectionExec>() {
                        let Some(plan) = node_ref.downcast_ref::<ProjectionExec>() else {
                            unreachable!()
                        };

                        let added_column = plan.input().schema().index_of(&alias)?;
                        let added_column = datafusion::physical_expr::expressions::Column::new(
                            &alias,
                            added_column,
                        );
                        let add_project =
                            ProjectionExpr::new(Arc::new(added_column), alias.clone());

                        let projections = plan.expr().iter().cloned().chain(once(add_project));

                        let project = ProjectionExec::try_new(projections, plan.input().clone())?;

                        Ok(Transformed::yes(Arc::new(project)))
                    } else {
                        Ok(Transformed::no(node))
                    }
                })?
                .data
        } else {
            input
        };

        let plan_display = DisplayableExecutionPlan::new(input.as_ref());
        trace!("UPDATE INPUT: {}", plan_display.indent(true));

        let (projected_input, schema, more_sinks) =
            self.project_insert_update(state, input, true)?;
        let sink = MySqlDmlSink::update(self.table_reference.clone(), schema)?;
        let sink = Self::chain_sink(Arc::new(sink), more_sinks);
        let exec = RecordBatchSinkExec::new(projected_input, sink);

        Ok(Arc::new(exec))
    }

    fn chain_sink(
        sink: Arc<dyn RecordBatchSink>,
        more_sinks: Vec<Arc<dyn RecordBatchSink>>,
    ) -> Arc<dyn RecordBatchSink> {
        if more_sinks.is_empty() {
            sink
        } else {
            let sink = more_sinks
                .into_iter()
                .fold(MultiplexSink::one(sink), |mut acc, elem| {
                    acc.add_sink(elem);
                    acc
                });

            Arc::new(sink)
        }
    }

    /// Returns:
    /// - an execution plan with all the columns required to insert/update + for the possible index sinks
    /// - the schema to send to insert/update
    /// - the index sinks
    fn project_insert_update(
        &self,
        state: &dyn Session,
        input: Arc<dyn ExecutionPlan>,
        is_update: bool,
    ) -> datafusion::common::Result<(
        Arc<dyn ExecutionPlan>,
        SchemaRef,
        Vec<Arc<dyn RecordBatchSink>>,
    )> {
        // can we find encrypted info in the input schema?
        trace!("Project insert/update: {:?}", input.schema());
        let key_manager = state.config().get_long_term_keys_manager();

        // Columns requested by the indexes - must be available in plaintext
        let requested_cleartext_columns = self
            .encryption_metadata
            .indices()
            .iter()
            .flat_map(|index| index.tracked_columns())
            .collect::<FxHashSet<ColumnName>>();

        let index_insert_strategies = self
            .encryption_metadata
            .indices()
            .iter()
            .map(|index| {
                if is_update {
                    Arc::clone(index).update(self, key_manager.clone(), input.schema().clone())
                } else {
                    Arc::clone(index).insert(self, key_manager.clone(), input.schema().clone())
                }
            })
            .collect::<Result<Vec<_>, _>>()?;

        // Split the index insert strategies among those that are forwarded to the main table, and those that are not
        let (forward, separate) = index_insert_strategies
            .into_iter()
            .partition::<Vec<_>, _>(|e| match e {
                IndexInsertStrategy::AddColumns(_) => true,
                IndexInsertStrategy::IndexSink(_) => false,
            });

        let forward_projections = forward
            .into_iter()
            .filter_map(|v| v.into_projection_vec())
            .flatten()
            .collect::<Vec<_>>();

        let (additional_projections, additional_sinks): (Vec<Vec<ProjectionExpr>>, Vec<_>) =
            separate
                .into_iter()
                .filter_map(|e| match e {
                    IndexInsertStrategy::IndexSink(index_sink) => Some((
                        index_sink.input().to_vec(),
                        index_sink.into_record_batch_sink(),
                    )),
                    _ => None,
                })
                .unzip();

        // TODO: some indices will require an additional sink

        // TODO: we may have column metadata that limit the size of the column (e.g. `VARCHAR(20) == max 20 chr`) ==> enforce these constraints here
        // TODO: we may want to move the encryption to a dedicated step - just think about how to maintain indexing info, maybe project as additional columns that get stripped by the sink?

        // Encrypted columns metadata, in the same order as the schema
        let encrypted_columns = input
            .schema()
            .fields()
            .iter()
            .map(|field| {
                self.get_column_metadata(field.name()).map(|meta| {
                    let cipher = key_manager.get_cipher(&CipherContext::TableColumn {
                        table_name: self.table_reference.table(),
                        column_name: field.name(),
                    });
                    let aad = AssociatedData::column_with_type(
                        self.table_reference.table(),
                        field.name(),
                        &meta.original_type,
                    );
                    (cipher, aad)
                })
            })
            .collect::<Vec<_>>();

        // Project layer 1:
        // - cleartext: do nothing
        // - encrypted w/ index: binary encode (to same column)
        // - encrypted w/o index: binary encode + encrypt (to same column)
        // Question: could the optimizer detect that we're doing the same op twice in cases 2 & 3 and simplify the logic?
        let input_schema = input.schema();
        let project_layer_1 = input_schema
            .fields()
            .iter()
            .zip(encrypted_columns.iter())
            .enumerate()
            .map(|(idx, (field, column_meta))| {
                let base = datafusion::physical_expr::expressions::Column::new(field.name(), idx);

                let expr = match column_meta {
                    None => Arc::new(base) as Arc<dyn PhysicalExpr>,
                    Some((cipher, aad)) => {
                        let cast =
                            Arc::new(ToBinaryExpr::new(Arc::new(base))) as Arc<dyn PhysicalExpr>;

                        if requested_cleartext_columns.contains(field.name()) {
                            // Return the column as-is
                            cast
                        } else {
                            let decrypt = EncryptExpr::new(cast, cipher.clone(), aad.clone());
                            Arc::new(decrypt) as Arc<dyn PhysicalExpr>
                        }
                    }
                };

                ProjectionExpr::new(expr, field.name().clone())
            });

        let project_layer_1 =
            Arc::new(ProjectionExec::try_new(project_layer_1, input)?) as Arc<dyn ExecutionPlan>;

        let (insert_schema, projected_input) = if requested_cleartext_columns.is_empty()
            && forward_projections.is_empty()
            && additional_projections.is_empty()
        {
            (project_layer_1.schema(), project_layer_1)
        } else {
            // Project layer 2
            // - cleartext w/ index: encode + convert (to new column)
            // - encrypted w/ index: encrypt source column + convert second column
            let project_layer_2_base = input_schema
                .fields()
                .iter()
                .zip(encrypted_columns.iter())
                .enumerate()
                .map(|(idx, (field, column_meta))| {
                    let base = Arc::new(physical_expr::expressions::Column::new(field.name(), idx));
                    let expr = match column_meta {
                        Some((cipher, aad))
                            if requested_cleartext_columns.contains(field.name()) =>
                        {
                            Arc::new(EncryptExpr::new(base, cipher.clone(), aad.clone()))
                                as Arc<dyn PhysicalExpr>
                        }
                        _ => base as Arc<dyn PhysicalExpr>,
                    };

                    ProjectionExpr::new(expr, field.name().clone())
                });

            let keep_columns = project_layer_1.schema().fields().len() + forward_projections.len();
            let project_layer_2 = project_layer_2_base
                .chain(forward_projections.into_iter())
                .chain(additional_projections.into_iter().flatten())
                .collect::<Vec<_>>();

            let project = Arc::new(ProjectionExec::try_new(project_layer_2, project_layer_1)?)
                as Arc<dyn ExecutionPlan>;

            // Only keep base columns + forward_projections. Order should be correct
            let mut new_schema = project.schema().fields().to_vec();
            new_schema.truncate(keep_columns);
            let new_schema = Schema::new(new_schema);

            (Arc::new(new_schema), project)
        };

        Ok((projected_input, insert_schema, additional_sinks))
    }
}

#[derive(Debug, Eq, PartialEq, Hash)]
struct GenerateRandomValue(IndexableColumnSize);

impl Display for GenerateRandomValue {
    fn fmt(&self, f: &mut Formatter<'_>) -> std::fmt::Result {
        self.fmt_sql(f)
    }
}

impl PhysicalExpr for GenerateRandomValue {
    fn as_any(&self) -> &dyn Any {
        self
    }

    fn data_type(&self, _input_schema: &Schema) -> datafusion::common::Result<DataType> {
        Ok(DataType::Binary)
    }

    fn nullable(&self, _input_schema: &Schema) -> datafusion::common::Result<bool> {
        Ok(false)
    }

    fn evaluate(&self, batch: &RecordBatch) -> datafusion::common::Result<ColumnarValue> {
        let mut builder =
            BinaryBuilder::with_capacity(batch.num_rows(), batch.num_rows() * self.0.bytes());
        let mut buffer = vec![0; self.0.bytes()];
        for _ in 0..batch.num_rows() {
            rng().fill_bytes(buffer.as_mut_slice());
            builder.append_value(&buffer);
        }
        Ok(ColumnarValue::Array(Arc::new(builder.finish())))
    }

    fn children(&self) -> Vec<&Arc<dyn PhysicalExpr>> {
        vec![]
    }

    fn with_new_children(
        self: Arc<Self>,
        _children: Vec<Arc<dyn PhysicalExpr>>,
    ) -> datafusion::common::Result<Arc<dyn PhysicalExpr>> {
        Ok(self)
    }

    fn fmt_sql(&self, f: &mut Formatter<'_>) -> std::fmt::Result {
        write!(f, "GenerateRandomValue({})", self.0.bytes())
    }
}
