[package]
name = "benchmarks"
version = "0.1.0"
edition = "2024"

[dependencies]
tar = "0.4.44"
flate2 = "1.1.5"
sha2 = "0.10.9"
mail-parser = { version = "0.11.1", features = ["serde"], optional = true }
reqwest = { version = "0.13.1", default-features = false, features = ["blocking", "http2", "native-tls"] }
hex-literal = "1.1.0"
mysql = "26.0.1"
log = "0.4.29"

[features]
default = ["enron"]
email = ["dep:mail-parser"]
enron = ["email"]