[package]
name = "crypto"
version = "0.1.0"
edition = "2024"

[dependencies]
log = { workspace = true }
hybrid-array = { workspace = true }
hex = { workspace = true }

hkdf = "0.13.0"
sha2 = "0.11.0"
aead = { version = "0.6.0-rc.10", features = ["alloc", "bytes"] }
rand = { workspace = true }
serde = { version = "1.0.228", features = ["derive"] }

datafusion = { workspace = true }
common = { path = "../common" }

zerocopy = "0.8.27"

rustc-hash = { workspace = true }

chacha20poly1305 = { version = "0.11.0-rc.3", features = ["reduced-round"], optional = true }
aes-gcm = { version = "0.11.0-rc.3", optional = true }
aws-lc-rs = { version = "1.16.3", optional = true }
tracing = { workspace = true }

[dev-dependencies]
criterion = { version = "0.8.2" }
snmalloc-rs = "0.7.4"
ccm = "0.6.0-rc.3"
deoxys = "0.2.0-rc.3"
eax = "0.6.0-rc.3"


[features]
default = ["crypto_all"]

crypto_all = ["rustcrypto_aes", "rustcrypto_chacha", "crypto_aws_lc"]
rustcrypto_aes = ["dep:aes-gcm"]
rustcrypto_chacha = ["dep:chacha20poly1305"]
crypto_aws_lc = ["dep:aws-lc-rs"]
tracing = []

[lints]
workspace = true

[[bench]]
name = "crypto_compare"
harness = false